# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F4xkXcyiVlvUGOIYUWjJIVZePFjLxCVm
"""

with open("app.py", "w") as f:
    f.write("""import streamlit as st
import openai

st.set_page_config(page_title="GPT-4.1-mini Chat", layout="wide")

api_key = st.text_input("OpenAI API Key를 입력하세요", type="password")
if api_key:
    st.session_state.api_key = api_key

page = st.sidebar.selectbox("페이지 선택", ["Chat"])

if "messages" not in st.session_state:
    st.session_state.messages = []

if page == "Chat":
    st.title("💬 GPT-4.1-mini Chatbot")

    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    user_input = st.chat_input("메시지를 입력하세요")

    if user_input:
        st.session_state.messages.append({"role": "user", "content": user_input})

        openai.api_key = st.session_state.api_key
        with st.chat_message("assistant"):
            with st.spinner("GPT 응답 생성 중..."):
                response = openai.ChatCompletion.create(
                    model="gpt-4-1106-preview",
                    messages=st.session_state.messages
                )
                answer = response.choices[0].message.content
                st.markdown(answer)

        st.session_state.messages.append({"role": "assistant", "content": answer})

    if st.button("Clear"):
        st.session_state.messages = []
""")

from google.colab import files
files.download("app.py")