# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F4xkXcyiVlvUGOIYUWjJIVZePFjLxCVm
"""

with open("app.py", "w") as f:
    f.write("""import streamlit as st
import openai

st.title("GPT-4.1-mini 응답 웹앱")

api_key = st.text_input("OpenAI API Key를 입력하세요", type="password")

if api_key:
    st.session_state.api_key = api_key

question = st.text_input("질문을 입력하세요")

@st.cache_data
def get_gpt_response(prompt):
    openai.api_key = st.session_state.api_key
    response = openai.ChatCompletion.create(
        model="gpt-4-1106-preview",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

if st.button("응답 받기"):
    if not api_key:
        st.warning("API Key를 먼저 입력하세요.")
    elif not question:
        st.warning("질문을 입력하세요.")
    else:
        with st.spinner("GPT 응답 생성 중..."):
            answer = get_gpt_response(question)
            st.success("✅ GPT 응답")
            st.write(answer)""")

from google.colab import files
files.download("app.py")